# Generated by Django 5.0.3 on 2024-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('Dystopia', 'Dystopia'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Spy', 'Spy'), ('Contemporary', 'Contemporary')], default='', max_length=20),
        ),
    ]
