# Generated by Django 5.0.3 on 2024-03-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dewscription',
            new_name='description',
        ),
    ]
