# Generated by Django 5.0.3 on 2024-04-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_dewscription_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.CharField(default='', max_length=80),
        ),
    ]
