# Generated by Django 5.0.3 on 2024-04-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_thumbnail_url_video_thumbnail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
