# Generated by Django 5.0.3 on 2024-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_video_thumbnail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
